version: '3.9'
services:
  php-fpm-webapi:
    build: .
    image: "web-api-image"
    container_name: web-api
    volumes:
      - ./:/var/www/html
      - ./.config/docker/php/jit.ini:/usr/local/etc/php/conf.d/jit.ini
      - ./.config/docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./.config/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.config/docker/php/header.ini:/usr/local/etc/php/conf.d/header.ini
    depends_on:
      - mysql
    networks:
      - my_network

  nginx:
    image: nginx:1.19.6
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/
      - ./.config/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm-webapi
    networks:
      - my_network

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "apiunialfa"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ./docs/db/mysql:/var/lib/mysql
      - ./docs/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
networks:
  my_network: